In [17]:
import json
import warnings
import pandas as pd

pd.set_option('future.no_silent_downcasting', True)
pd.set_option('display.max_columns', None)

warnings.filterwarnings('ignore')

In [18]:
df = pd.read_csv('powerBI/raw_data_with_predictions.csv')

In [19]:
vehicle_price_mapping = {
    'less than 20000': 20000,
    '20000 to 29000': 25000,
    '30000 to 39000': 35000,
    '40000 to 59000': 50000,
    '60000 to 69000': 65000,
    'more than 69000': 75000
}

df['VehiclePrice_average'] = df['VehiclePrice'].map(vehicle_price_mapping)

In [20]:
# df.FraudFound_P.value_counts()

In [21]:
df.to_csv("powerBI/raw_data.csv", index=False)

---

## EBM local scores

In [36]:
with open('powerBI/all_perils_ebm.json', 'r') as f:
    all_perils_ebm = json.load(f)

with open('powerBI/collision_ebm.json', 'r') as f:
    collision_ebm = json.load(f)

In [37]:
all_perils_ebm['ebm'].keys()

dict_keys(['outputs', 'intercept', 'bagged_intercept', 'bag_weights', 'best_iteration', 'implementation', 'implementation_params', 'features', 'terms'])

In [43]:
ap_category_db = pd.DataFrame()
ap_numeric_db = pd.DataFrame()

all_p_intercept = all_perils_ebm['ebm']['intercept']

for feature, term in zip(all_perils_ebm['ebm']['features'], all_perils_ebm['ebm']['terms']):
    if 'categories' in list(feature.keys()):
        print(feature['name'])
        value_df = pd.DataFrame(feature['categories']).T
        value_df.columns=['input_value']
        value_df['feature'] = feature['name']

        value_df['score'] = term['scores'][1:-1]
        value_df['score_std'] = term['standard_deviations'][1:-1]

        ap_category_db = pd.concat([ap_category_db, value_df], axis=0)
        
    else:
        print(">", feature['name'])
        # numerical feature들을 'binning'하여 score를 부여한 형태
        total_feature_cuts = [feature['min']] + feature['cuts'][0] + [feature['max']]
        tmp = pd.DataFrame(total_feature_cuts, columns=['cut_start'])
        tmp['cut_end'] = tmp.cut_start.shift(-1)
        tmp.dropna(inplace=True)
        tmp['feature'] = feature['name']

        tmp['score'] = term['scores'][1:-1]
        tmp['score_std'] = term['standard_deviations'][1:-1]
        # 따라서 각각의 bin에 따라 score가 분배 되어 있다
        tmp_df_list = list()

        for value in df[feature['name']].unique():
            extracted_tmp = tmp.loc[(tmp['cut_start']<=value) & (tmp['cut_end']>value)]
            extracted_tmp['input_value'] = value
            tmp_df_list.append(extracted_tmp)
        # 가장 마지막 value 값도 추가
        extracted_tmp = tmp.loc[tmp['cut_end']==feature['max']]
        extracted_tmp['input_value'] = feature['max']
        tmp_df_list.append(extracted_tmp)

        value_df = pd.concat(tmp_df_list, axis=0)
        ap_numeric_db = pd.concat([ap_numeric_db, value_df], axis=0)

        # if feature['name']=="DriverRating":
        #     break
        
ap_numeric_db.sort_values(['feature', 'input_value'], inplace=True)
ap_numeric_db.drop(columns=['cut_start', 'cut_end'], inplace=True)
ap_category_db['intercept'] = all_p_intercept[0]
ap_numeric_db['intercept'] = all_p_intercept[0]

Make
VehiclePrice_num
VehicleCategory
AgeOfVehicle
Sex
MaritalStatus
> Age
> DriverRating
AgeOfPolicyHolder
NumberOfCars
PastNumberOfClaims
PolicyType
> Deductible
AgentType
NumberOfSuppliments
Days_Policy_Accident
Days_Policy_Claim
PoliceReportFiled
WitnessPresent
AddressChange_Claim_2

({'name': 'Make',
  'type': 'nominal',
  'num_unique_vals': 17,
  'categories': [['Accura',
    'BMW',
    'Chevrolet',
    'Dodge',
    'Ford',
    'Honda',
    'Jaguar',
    'Mazda',
    'Mecedes',
    'Mercury',
    'Nisson',
    'Pontiac',
    'Porche',
    'Saab',
    'Saturn',
    'Toyota',
    'VW']]},
 {'term_features': ['Make'],
  'scores': [0.0,
   0.4723664744490646,
   -1.0410160842816447,
   -0.1874101227123349,
   -0.4046564910649314,
   -0.25190676874481177,
   -0.5325484535042988,
   -1.0383527608940952,
   -0.08763388926604124,
   -1.0045415449907833,
   -0.6121179225027065,
   -0.9721358247219473,
   0.3321393501865147,
   -0.9609770790952449,
   0.13529266805406057,
   -0.5195154880208418,
   -0.0014078569924194256,
   -0.4321577308259623,
   0.0],
  'standard_deviations': [0.0,
   0.061206813442847216,
   0.3870603545946905,
   0.04968338977445204,
   0.29716331220748643,
   0.06930045894769435,
   0.04273308196195984,
   0.39116254363251063,
   0.04261302345285889,
   0.39041111306791476,
   0.41543114240493856,
   0.3924394647218232,
   0.022210186631820554,
   0.39251703571266705,
   0.18620995688387112,
   0.2372315879441814,
   0.036269360524770346,
   0.11799255288602374,
   0.0],
  'bagged_scores': [[0.0,
    0.5468417879543587,
    -0.6607657143189681,
    -0.15094608191462816,
    -0.2766860619339536,
    -0.27323728681058423,
    -0.5780192473811921,
    -0.6649447610569821,
    -0.02272836571602089,
    -0.6295009566138932,
    -0.37024410887753706,
    -0.5986686444244826,
    0.3159962822380693,
    -0.6006009863049965,
    0.05259568339917775,
    -0.6235989206530074,
    -0.026709709603923014,
    -0.4062286888202844,
    0.0],
   [0.0,
    0.5539434203855148,
    -1.224054224719443,
    -0.11104802197432556,
    -0.04457138875402441,
    -0.24515511695087125,
    -0.5924227018034538,
    -1.2445611232636966,
    -0.04001674325404598,
    -1.2147013388379917,
    -0.8034719890537999,
    -1.1764718445835831,
    0.32635234848381933,
    -1.1654851907694237,
    -0.1808578748027126,
    -0.4942890910695831,
    -0.012950574340957477,
    -0.5722866936875687,
    0.0],
   [0.0,
    0.4717880056053375,
    -1.281846414665471,
    -0.19539063669325363,
    -1.307468319144109,
    -0.14015942495545514,
    -0.48678452025729935,
    -1.3065313977774664,
    -0.12056435882854181,
    -1.266865964851717,
    -0.3032330869156191,
    -1.2353137767757747,
    0.32217095479322994,
    -1.228306072135417,
    0.07636324868973166,
    -0.34228584425771746,
    -0.01870707172947115,
    -0.32509066063204983,
    0.0],
   [0.0,
    0.37355132252346185,
    -0.5181717903696267,
    -0.20973732592197258,
    -0.2553015559242064,
    -0.2964249546915688,
    -0.5282740772089525,
    -0.5121391361581668,
    -0.11420871826314465,
    -0.4799977430644112,
    -0.44559931760806754,
    -0.43120456376248123,
    0.31783575717415824,
    -0.4223567854125974,
    -0.02827916167889412,
    -0.4006118611092109,
    0.0593500411884564,
    -0.4931987548205187,
    0.0],
   [0.0,
    0.43454580582070285,
    -1.031198303634563,
    -0.15792070419786863,
    -0.6228034023583172,
    -0.34831708833529196,
    -0.47382675513440575,
    -1.0372026202191442,
    -0.20771524404974162,
    -1.0009051240228892,
    -0.460462619730309,
    -0.9665132526002296,
    0.3524761330717824,
    -0.9279787895300711,
    -0.06945029730900887,
    -0.35189461662296323,
    0.01762616051622428,
    -0.6480529989190819,
    0.0],
   [0.0,
    0.48737077135638834,
    -1.1086620128008047,
    -0.14325802334635285,
    -0.44333297908805597,
    -0.267825393590306,
    -0.527028822816405,
    -1.1072874263953902,
    -0.0543502050811303,
    -1.0695548998325615,
    -0.28082847756476276,
    -1.0397884504290635,
    0.3623210089183598,
    -1.0446990505668547,
    0.4209068868115906,
    -0.4330494359484063,
    -0.09377497474141167,
    -0.48594466952934734,
    0.0],
   [0.0,
    0.4256325417814272,
    -0.5956199739602518,
    -0.2046851918552378,
    -0.19268822928382706,
    -0.2576292449071746,
    -0.48548568513119433,
    -0.5893845220928302,
    -0.07562245258913271,
    -0.5701438749657277,
    -0.5590442637754974,
    -0.5434496147727208,
    0.2833555797334276,
    -0.543475439728434,
    0.08830189331986253,
    -0.4071470390625144,
    0.02850891128574346,
    -0.3170870585696119,
    0.0],
   [0.0,
    0.43153734475822114,
    -0.9112587354105305,
    -0.18380889475782022,
    -0.33949507535205486,
    -0.33186126940356314,
    -0.5966342559291864,
    -0.8742029725371346,
    -0.07209066762109709,
    -0.8480815189722644,
    -0.5743364734528286,
    -0.8259794815265636,
    0.33065014248489033,
    -0.8135333610870134,
    0.3762353760843276,
    -0.5176647169695744,
    0.03871289304570121,
    -0.38470050379465415,
    0.0],
   [0.0,
    0.41723539457709846,
    -1.2121824376809467,
    -0.24418948921745345,
    -0.29723098674122406,
    -0.19929760881700737,
    -0.49017559382318865,
    -1.1861024006419922,
    -0.10164513867331865,
    -1.153636925619527,
    -0.521459518738615,
    -1.1219592170765447,
    0.3705199757024562,
    -1.1176992765136857,
    0.49563474094886395,
    -1.1315661985209335,
    -0.02528842404153879,
    -0.5750376364462567,
    0.0],
   [0.0,
    0.49159174309435916,
    -1.0445553011610527,
    -0.2544021960930031,
    -0.07427834843902106,
    -0.37333074238789943,
    -0.5171320099463229,
    -1.038949903938612,
    -0.09192237844259017,
    -1.0051597179893537,
    -0.6297821460632375,
    -0.9705372986580765,
    0.3441395462087582,
    -0.9436486194253191,
    0.011313937965818434,
    -0.18993841846302367,
    0.010172070192594066,
    -0.410637645225659,
    0.0],
   [0.0,
    0.5491526909300942,
    -2.08351060192779,
    -0.10573350533002294,
    -0.4112711682110439,
    -0.14158139053967056,
    -0.5687884967726264,
    -2.089057876441779,
    -0.10488689610881168,
    -2.0600941337056176,
    -1.9578145570396375,
    -2.0300032148345397,
    0.3132009169404691,
    -2.0298911105481428,
    0.08522764859294518,
    -0.8251064220544873,
    0.031234435297557477,
    -0.24223786286600602,
    0.0],
   [0.0,
    0.47421601143129255,
    -1.049398535065674,
    -0.1654155200987799,
    -0.47869983954269246,
    -0.2532746000472795,
    -0.5423852909504567,
    -1.0690110481624708,
    -0.07675244560251787,
    -1.020032973416896,
    -0.9432496575399919,
    -0.9813879194115923,
    0.34944867453348594,
    -0.9753440745063243,
    0.26229421210601733,
    -0.7818856533043723,
    -0.02019807223508411,
    -0.4129740396488333,
    0.0],
   [0.0,
    0.38952703677723677,
    -1.2624106600609104,
    -0.2226327865593801,
    -0.5658396977682114,
    -0.22245279176349383,
    -0.4866629281985502,
    -1.2387348989251175,
    -0.08025168084336815,
    -1.2011872318574945,
    -0.4088780118272779,
    -1.18267851378299,
    0.34343415236114844,
    -1.1461746566194475,
    0.14054765433988956,
    -0.35424297891365236,
    -0.011551157932030216,
    -0.5173334728801107,
    0.0],
   [0.0,
    0.5661967652914114,
    -0.5905904741669926,
    -0.2745733400125898,
    -0.3555238223682986,
    -0.17614784922719848,
    -0.5820579637069498,
    -0.5788285649065494,
    -0.06411915465111596,
    -0.5437192261206218,
    -0.3112466868507089,
    -0.5059457534686207,
    0.31804942996715047,
    -0.49448569418569943,
    0.16326340428923847,
    -0.41993563534233946,
    0.0038654752042675614,
    -0.2593975457234903,
    0.0]],
  'bin_weights': [0.0,
   265.0,
   5.0,
   448.0,
   14.0,
   163.0,
   588.0,
   1.0,
   430.0,
   1.0,
   31.0,
   9.0,
   1309.0,
   1.0,
   28.0,
   24.0,
   1005.0,
   75.0,
   0.0]})

In [25]:
ap_numeric_db['policy_type'] = "All Perils"
ap_numeric_db['feature_type'] = "numeric"
ap_category_db['policy_type'] = "All Perils"
ap_category_db['feature_type'] = "category"

all_p_local_scores = pd.concat([ap_numeric_db, ap_category_db], axis=0)

In [45]:
all_p_local_scores

,feature,score,score_std,input_value,intercept,policy_type,feature_type
0,Age,1.141860,0.506628,0.0,-1.211982,All Perils,numeric
1,Age,1.129908,0.506179,16.0,-1.211982,All Perils,numeric
1,Age,1.129908,0.506179,17.0,-1.211982,All Perils,numeric
1,Age,1.129908,0.506179,18.0,-1.211982,All Perils,numeric
2,Age,1.623872,1.111519,19.0,-1.211982,All Perils,numeric
...,...,...,...,...,...,...,...
1,PoliceReportFiled,-2.259771,0.228416,Yes,-1.211982,All Perils,category
0,WitnessPresent,0.008652,0.003212,No,-1.211982,All Perils,category
1,WitnessPresent,-1.400391,0.519933,Yes,-1.211982,All Perils,category
0,AddressChange_Claim_2,-0.074757,0.281110,change,-1.211982,All Perils,category
1,AddressChange_Claim_2,0.005123,0.019264,no_change,-1.211982,All Perils,category

In [27]:
c_category_db = pd.DataFrame()
c_numeric_db = pd.DataFrame()

collision_intercept = collision_ebm['ebm']['intercept']

for feature, term in zip(collision_ebm['ebm']['features'], collision_ebm['ebm']['terms']):
    if 'categories' in list(feature.keys()):
        print(feature['name'])
        value_df = pd.DataFrame(feature['categories']).T
        value_df.columns=['input_value']
        value_df['feature'] = feature['name']

        value_df['score'] = term['scores'][1:-1]
        value_df['score_std'] = term['standard_deviations'][1:-1]

        c_category_db = pd.concat([c_category_db, value_df], axis=0)
    else:
        print(">", feature['name'])
        # numerical feature들을 'binning'하여 score를 부여한 형태
        total_feature_cuts = [feature['min']] + feature['cuts'][0] + [feature['max']]
        tmp = pd.DataFrame(total_feature_cuts, columns=['cut_start'])
        tmp['cut_end'] = tmp.cut_start.shift(-1)
        tmp.dropna(inplace=True)
        tmp['feature'] = feature['name']

        tmp['score'] = term['scores'][1:-1]
        tmp['score_std'] = term['standard_deviations'][1:-1]
        # 따라서 각각의 bin에 따라 scorer가 분배 되어 있다
        tmp_df_list = list()

        for value in df[feature['name']].unique():
            extracted_tmp = tmp.loc[(tmp['cut_start']<=value) & (tmp['cut_end']>value)]
            extracted_tmp['input_value'] = value
            tmp_df_list.append(extracted_tmp)
        # 가장 마지막 value 값도 추가
        extracted_tmp = tmp.loc[tmp['cut_end']==feature['max']]
        extracted_tmp['input_value'] = feature['max']
        tmp_df_list.append(extracted_tmp)

        value_df = pd.concat(tmp_df_list, axis=0)
        c_numeric_db = pd.concat([c_numeric_db, value_df], axis=0)
        
c_numeric_db.sort_values(['feature', 'input_value'], inplace=True)
c_numeric_db.drop(columns=['cut_start', 'cut_end'], inplace=True)
c_category_db['intercept'] = collision_intercept[0]
c_numeric_db['intercept'] = collision_intercept[0]

Make
VehiclePrice_num
VehicleCategory
AgeOfVehicle
Sex
MaritalStatus
> Age
> DriverRating
AgeOfPolicyHolder
NumberOfCars
PastNumberOfClaims
PolicyType
> Deductible
AgentType
NumberOfSuppliments
Days_Policy_Accident
Days_Policy_Claim
PoliceReportFiled
WitnessPresent
AddressChange_Claim_2

In [28]:
c_numeric_db['policy_type'] = "Collision"
c_numeric_db['feature_type'] = "numeric"
c_category_db['policy_type'] = "Collision"
c_category_db['feature_type'] = "category"

collision_local_scores = pd.concat([c_numeric_db, c_category_db], axis=0)

In [29]:
collision_local_scores

,feature,score,score_std,input_value,intercept,policy_type,feature_type
0,Age,0.680777,0.421597,0.0,-1.544721,Collision,numeric
1,Age,0.688154,0.419041,16.0,-1.544721,Collision,numeric
2,Age,0.784149,0.562550,17.0,-1.544721,Collision,numeric
3,Age,0.739739,0.469851,18.0,-1.544721,Collision,numeric
4,Age,0.725152,0.457805,19.0,-1.544721,Collision,numeric
...,...,...,...,...,...,...,...
1,PoliceReportFiled,-1.656425,0.208260,Yes,-1.544721,Collision,category
0,WitnessPresent,0.009074,0.001389,No,-1.544721,Collision,category
1,WitnessPresent,-1.369445,0.209649,Yes,-1.544721,Collision,category
0,AddressChange_Claim_2,0.181922,0.143245,change,-1.544721,Collision,category
1,AddressChange_Claim_2,-0.014050,0.011063,no_change,-1.544721,Collision,category

In [46]:
local_scores = pd.concat([collision_local_scores, all_p_local_scores], axis=0)
local_scores.to_csv("powerBI/local_scores.csv", index=False)

---

In [47]:
local_scores

,feature,score,score_std,input_value,intercept,policy_type,feature_type
0,Age,0.680777,0.421597,0.0,-1.544721,Collision,numeric
1,Age,0.688154,0.419041,16.0,-1.544721,Collision,numeric
2,Age,0.784149,0.562550,17.0,-1.544721,Collision,numeric
3,Age,0.739739,0.469851,18.0,-1.544721,Collision,numeric
4,Age,0.725152,0.457805,19.0,-1.544721,Collision,numeric
...,...,...,...,...,...,...,...
1,PoliceReportFiled,-2.259771,0.228416,Yes,-1.211982,All Perils,category
0,WitnessPresent,0.008652,0.003212,No,-1.211982,All Perils,category
1,WitnessPresent,-1.400391,0.519933,Yes,-1.211982,All Perils,category
0,AddressChange_Claim_2,-0.074757,0.281110,change,-1.211982,All Perils,category
1,AddressChange_Claim_2,0.005123,0.019264,no_change,-1.211982,All Perils,category

In [48]:
products = df[['BasePolicy']].drop_duplicates()
products.to_csv("powerBI/products.csv", index=True)
products

   BasePolicy
0   Liability
1   Collision
9  All Perils

---

In [52]:
time_vars = ["Month", "WeekOfMonth", "DayOfWeek", "DayOfWeekClaimed", 'MonthClaimed', 'WeekOfMonthClaimed', 'Year']
vehicle_vars = ["Make", "VehiclePrice_num", "VehicleCategory", "AgeOfVehicle", "VehiclePrice", "VehiclePrice_average"]
personal_vars = ["Sex", 'MaritalStatus', "Age", 'DriverRating', 'AgeOfPolicyHolder', 'NumberOfCars', 'PastNumberOfClaims', 'AddressChange_Claim']
policy_vars = ["PolicyType", 'Deductible', 'AgentType', "NumberOfSuppliments", 'PolicyNumber', 'RepNumber', 'BasePolicy']
accident_vars = ['Days_Policy_Accident', 'Days_Policy_Claim', 'PoliceReportFiled', 'WitnessPresent', 'AddressChange_Claim_2', 'AccidentArea', 'Fault', 'FraudFound_P', 'predictions']

In [53]:
time_df = pd.DataFrame(time_vars, columns=['feature'])
time_df['feature_type'] = 'time'

vehicle_df = pd.DataFrame(vehicle_vars, columns=['feature'])
vehicle_df['feature_type'] = 'vehicle'

personal_df = pd.DataFrame(personal_vars, columns=['feature'])
personal_df['feature_type'] = 'personal'

policy_df = pd.DataFrame(policy_vars, columns=['feature'])
policy_df['feature_type'] = 'policy'

accident_df = pd.DataFrame(accident_vars, columns=['feature'])
accident_df['feature_type'] = 'accident'

features = pd.concat([time_df, vehicle_df, personal_df, policy_df, accident_df], axis=0)

In [54]:
features

                 feature feature_type
0                  Month         time
1            WeekOfMonth         time
2              DayOfWeek         time
3       DayOfWeekClaimed         time
4           MonthClaimed         time
5     WeekOfMonthClaimed         time
6                   Year         time
0                   Make      vehicle
1       VehiclePrice_num      vehicle
2        VehicleCategory      vehicle
3           AgeOfVehicle      vehicle
4           VehiclePrice      vehicle
5   VehiclePrice_average      vehicle
0                    Sex     personal
1          MaritalStatus     personal
2                    Age     personal
3           DriverRating     personal
4      AgeOfPolicyHolder     personal
5           NumberOfCars     personal
6     PastNumberOfClaims     personal
7    AddressChange_Claim     personal
0             PolicyType       policy
1             Deductible       policy
2              AgentType       policy
3    NumberOfSuppliments       policy
4           PolicyNumber       policy
5              RepNumber       policy
6             BasePolicy       policy
0   Days_Policy_Accident     accident
1      Days_Policy_Claim     accident
2      PoliceReportFiled     accident
3         WitnessPresent     accident
4  AddressChange_Claim_2     accident
5           AccidentArea     accident
6                  Fault     accident
7           FraudFound_P     accident
8            predictions     accident

In [55]:
features.to_csv("powerBI/features.csv", index=False)
features.tail(3)

        feature feature_type
6         Fault     accident
7  FraudFound_P     accident
8   predictions     accident

---